default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: embudos_adm
  database: embudos_dev

test:
  <<: *default
  username: embudos_adm
  database: embudos_test

production:
  <<: *default
  host: <%= ENV['OPENSHIFT_POSTGRESQL_DB_HOST'] %>
  port: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PORT'] %>
  username: <%= ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] %>
